name: 'makensis'
description: 'Nullsoft scriptable install system action'
inputs:
  script-file:
    description: 'Path to the .nsi script file'
    required: false
    default: 'install.nsi'

  arguments:
    description: 'Arguments to makensis.exe'
    required: false
    default: ''

  additional-plugin-paths:
    description: 'Newline-delimited list of paths to load plugins from'
    required: false
    default: ''

  defines:
    description: 'Newline-delimited list of key-value pairs to define variables'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.cjs'

branding:
  icon: 'triangle'
  color: 'blue'
